import { error } from '@sveltejs/kit';
import type { PageServerLoad } from './$types.js';
import { Client } from 'pve-client';
import { createClient, extractPrimaryContainerIPv4, buildBridgeWsUrlFromIpv4, resolveLxcBridgeWsUrl, isIPv4Address } from '../helpers.js';
import type { LxcInterface } from '../types.js';

export const load: PageServerLoad = async ({ url }) => {
  const vmidStr = url.searchParams.get('vmid');
  const node = url.searchParams.get('node');
  const type = url.searchParams.get('type');
  const name = url.searchParams.get('name');
  const knownIp = url.searchParams.get('ip')?.trim();

  if (!vmidStr || !node || (type !== 'vm' && type !== 'container')) {
    error(400, 'Missing or invalid vmid, node, or type query parameters');
  }

  const vmid = parseInt(vmidStr, 10);
  if (!Number.isInteger(vmid) || vmid <= 0) {
    error(400, `Invalid vmid: ${vmidStr}`);
  }

  const bridgeTemplate = process.env.LXC_VNC_BRIDGE_WS_URL?.trim();
  const deriveBridgeFromIpv4 = process.env.LXC_VNC_BRIDGE_DERIVE_FROM_IPV4 === 'true';

  // VMs always use native Proxmox VNC (vncproxy). Containers always use bridge
  // mode (websockify on the guest). There is no cross-fallback between modes.
  if (type === 'vm') {
    // Native Proxmox VNC for VMs
    let info: Awaited<ReturnType<ReturnType<Client['helpers']['display']>['getConnectionInfo']>>;
    try {
      // noVNC must answer the RFB password challenge with the temporary ticket
      // password generated by Proxmox vncproxy, not the account/root password.
      const client = await createClient();
      const display = client.helpers.display(vmid);
      info = await display.getConnectionInfo();
    } catch (err) {
      console.error('[vnc-page] Failed to prepare VNC connection info:', err);
      error(503, 'Unable to prepare VNC session. Please verify VM state and Proxmox credentials.');
    }

    const vncPassword = info.ticket.password ?? info.ticket.ticket;

    return {
      vmid,
      node,
      type,
      name: name?.trim() || null,
      upstreamWsUrl: info.websocketUrl,
      vncPassword,
      vncUsername: info.ticket.user,
    };
  }

  // Container (LXC) — bridge mode only
  if (!bridgeTemplate && !deriveBridgeFromIpv4) {
    error(
      503,
      'Bridge mode is not configured for container VNC (set LXC_VNC_BRIDGE_DERIVE_FROM_IPV4 or LXC_VNC_BRIDGE_WS_URL).'
    );
  }

  let bridgeWsUrl: string | undefined;
  try {
    const primaryIpv4 = (() => {
      if (knownIp && isIPv4Address(knownIp) && !knownIp.startsWith('127.') && !knownIp.startsWith('169.254.')) {
        return knownIp;
      }
      return undefined;
    })();

    let resolvedIpv4 = primaryIpv4;
    if (!resolvedIpv4) {
      const client = await createClient();
      const nodeApi = client.api.nodes.get(node);

      const interfaces = await nodeApi.lxc.id(vmid).interfaces() as LxcInterface[];
      resolvedIpv4 = extractPrimaryContainerIPv4(interfaces);
    }

    if (!resolvedIpv4) {
      error(503, `Unable to determine container IPv4 address (vmid ${vmid}). The guest IP must be resolved for GUI bridge mode.`);
    }

    if (bridgeTemplate) {
      bridgeWsUrl = resolveLxcBridgeWsUrl(bridgeTemplate, node, vmid, resolvedIpv4);
    } else {
      bridgeWsUrl = buildBridgeWsUrlFromIpv4(resolvedIpv4);
    }
  } catch (err) {
    if (typeof err === 'object' && err !== null && 'status' in err && typeof err.status === 'number') {
      throw err;
    }

    console.error('[vnc-page] Invalid guest bridge websocket settings for container', vmid, ':', err);
    error(500, 'Invalid guest bridge websocket configuration.');
  }

  if (bridgeWsUrl) {
    return {
      vmid,
      node,
      type,
      name: name?.trim() || null,
      upstreamWsUrl: bridgeWsUrl,
      vncPassword: '',
      vncUsername: null,
    };
  }

  error(500, 'Failed to resolve bridge URL for container VNC.');
};
