import { error } from '@sveltejs/kit';
import type { PageServerLoad } from './$types.js';
import { Client } from 'pve-client';
import { Agent } from 'node:https';

const createClient = async (): Promise<Client> => {
  const baseUrl = process.env.PVE_BASE_URL;
  const apiToken = process.env.PVE_API_TOKEN?.trim() || undefined;
  const username = process.env.PVE_USERNAME?.trim() || undefined;
  const password = process.env.PVE_PASSWORD?.trim() || undefined;
  const realm = process.env.PVE_REALM?.trim() || 'pam';
  const insecureTls = process.env.PVE_INSECURE_TLS === 'true';

  if (!baseUrl) throw new Error('PVE_BASE_URL not configured');

  const agent = insecureTls ? new Agent({ rejectUnauthorized: false }) : undefined;

  if (apiToken) {
    return new Client({ baseUrl, apiToken, agent });
  }

  if (username && password) {
    const client = new Client({ baseUrl, username, password, realm, agent });
    await client.login();
    return client;
  }

  throw new Error('No Proxmox credentials configured');
};

export const load: PageServerLoad = async ({ url }) => {
  const vmidStr = url.searchParams.get('vmid');
  const node = url.searchParams.get('node');
  const type = url.searchParams.get('type');
  const name = url.searchParams.get('name');

  if (!vmidStr || !node || (type !== 'vm' && type !== 'container')) {
    error(400, 'Missing or invalid vmid, node, or type query parameters');
  }

  const vmid = parseInt(vmidStr, 10);
  if (!Number.isInteger(vmid) || vmid <= 0) {
    error(400, `Invalid vmid: ${JSON.stringify(vmidStr)}`);
  }

  let info: Awaited<ReturnType<ReturnType<Client['helpers']['display']>['getConnectionInfo']>>;
  try {
    // noVNC must answer the RFB password challenge with the temporary ticket
    // password generated by Proxmox vncproxy, not the account/root password.
    const client = await createClient();
    const display = client.helpers.display(vmid);
    info = await display.getConnectionInfo();
  } catch (err) {
    console.error('[vnc-page] Failed to prepare VNC connection info:', err);
    error(503, 'Unable to prepare VNC session. Please verify VM state and Proxmox credentials.');
  }

  const vncPassword = info.ticket.password ?? info.ticket.ticket;

  return {
    vmid,
    node,
    type,
    name: name?.trim() || null,
    upstreamWsUrl: info.websocketUrl,
    vncPassword,
    vncUsername: info.ticket.user,
  };
};
